# Generated by Django 5.1 on 2025-07-08 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pedido_producto_pedido_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.CreateModel(
            name='PedidoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.products')),
            ],
        ),
    ]
