# Generated by Django 5.1 on 2025-09-01 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
