# Generated by Django 5.1 on 2025-07-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pedido_cliente_remove_pedidoitems_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
