# Generated by Django 5.1 on 2025-07-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pedido_direccion_alter_pedido_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
