# Generated by Django 5.1 on 2025-07-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pedido_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.TextField(),
        ),
    ]
