# Generated by Django 5.1 on 2025-07-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pedido_direccion_alter_pedido_productos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha']},
        ),
    ]
